GET http://localhost:3000/bodys

###
###
GET http://localhost:3000/bodys/2
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJiQGIuY29tIiwiY29tcGFueSI6IkFDTUUiLCJleHAiOjIwMDAwMDAwMDB9.def6AUTwTFvyiysNVBIvdBovkN22_PbBovzGKaJAONE


###
GET http://localhost:3000/protected
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiaGVsbG8iLCJzdWIiOiJiQGIuY29tIiwiY29tcGFueSI6IkFDTUUiLCJleHAiOjIwMDAwMDAwMDB9.HlvHZEu5dTXyzna6UxH4nAwW8YumZdZSq9t_Mdz3h3A

###
POST http://localhost:3000/authorize HTTP/1.1
content-type: application/json

{
    "client_id": "foo",
    "client_secret": "bar"
}